name: "CoderDojo Melvindale"
tagline: "Code Young! Code Long!"

url: "https://melcoderdojo.github.io"

paginate: 5

markdown: redcarpet
permalink: /:year/:month/:title/
timezone: US/Eastern

highlighter: pygments
excerpt_separator: <!--more-->
gems:
  - jemoji

navigation:
  - text: Home
    url: /
    title: Go home
  - text: About
    url: /about
    title: What is this?
  - text: Volunteer
    url: /volunteer
    title: Want to help?
  - text: Contact
    url: /contact
    title: Shoot us a message

media:
  - text: Twitter
    url: https://twitter.com/MelCoderDojo
    title: We're on Twitter
    image: /img/twitter-circle.png
  - text: Facebook
    url: https://www.facebook.com/pages/CoderDojo-Melvindale/711828098898791
    title: We're on Facebook
    image: /img/facebook-circle.png
  - text: RSS
    url: https://twitter.com/MelCoderDojo
    title: RSS Feed
    image: /img/rss-circle.png
